### PR TITLE
[release-1.4] Channel host based routing

### PR DESCRIPTION
**Pull request by matzew**
The 1.4 version of #2164

### CODE REVIEW

**Comment by matzew** [comment]
I see 

```

        - 			`path":"/test-nc/kc`,
        + 			`host":"kc-kn-channel.test-nc.svc.cluster.local`,
          			`"}, "egresses":[{"consumerGroup":"kafka.test-nc.kc.2f9b5e8e-deb6`,
``` 

locally too

**Comment by matzew** [comment]
looking

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
