### PR TITLE
Improve testing pipeline

### PR DESCRIPTION
**Pull request by pierDipi**
## Proposed Changes

- Skip tests (unit and checkstyle) when building components images
- Remove duplicated Dockerfile and use only one with build arguments

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Ok so this dockerfile is just meant for release and e2e testing right? Now we need another one where we run unit tests in java (using `mvn verify`)

**Comment by pierDipi** [comment]
We have it here: https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/data-plane/docker/test/Dockerfile

**Comment by pierDipi** [comment]
> Ok so this dockerfile is just meant for release and e2e testing right?

Correct.

**Pull request merged**
