### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by evankanderson**

### CODE REVIEW

**Comment by evankanderson** [comment]
/hold

This is to verify Prow is set up correctly (https://github.com/knative/test-infra/pull/2222)

**Comment by evankanderson** [comment]
/hold cancel

I'll add test files to make things happy

**Comment by pierDipi** [comment]
> I'll add test files to make things happy

I did this for you here: https://github.com/knative-sandbox/eventing-kafka-broker/pull/4

**Comment by slinkydeveloper** [comment]
Can you rebase on master?

**Pull request merged**
