### PR TITLE
Added Egress uid and renamed Resource id to uid

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Part of #279

As proposed in https://github.com/knative-sandbox/eventing-kafka-broker/compare/master...slinkydeveloper:issues/279_part_2, I wish to modify the reconciliation logic to use uid as index more than the hash of the wrapper resources themselves. This adds uid to Egress (because consumer group may not be always the same as kube uid) and renamed Resource.id to Resource.uid to clarify that the id is unique and relates to kube uid.

## Proposed Changes

- Added uid field to egress
- Renamed id field of Resource to uid to clarify it (and make it consistent with egress uid)

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
Can you update codegen?

/approve

**Comment by slinkydeveloper** [comment]
the lint doesn't pass for the trailing whitespace :)

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
I have a PR open to fix it: https://github.com/knative-sandbox/.github/pull/63/files

**Comment by slinkydeveloper** [comment]
That's weird, the config map is there (I'm looking here https://00f74ba44b977ed75f1f1c180f01ae3cbf82d82e75-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/pr-logs%2Fpull%2Fknative-sandbox_eventing-kafka-broker%2F310%2Fpull-knative-sandbox-eventing-kafka-broker-integration-tests%2F1318185319446614016%2Fartifacts%2F9f9b608a-1210-11eb-8ffa-c2dc0fa0ae6d%2Fk8s.dump-e2e-tests.sh.txt?jk=AFshE3XfW9ZKvmKtvFa8WK8TNaF8wkl6DBP3ng4YbtTeDfV9pL8LPmIIbWkTbVXoE6nwVZs1v30izmrSy-1aMMZxNPwI9MhBW5FlWMfVjgoioGGfVhecIlrjDv6SmkONBHJ9H-ezhzFxxEuf4POPzDQO9Bln3n4nJNd9cN61TKpqAZXZbD2Gqaj0Ie6Tz9FllsPer3m-oOjoZ20m6KwDZu8Np8OfuIHfZ6JSBMsB4wDm2OJmmpLNRgo6wXzxYKWIzrn2s82u3GghnHwfr1cmf25_AWLcrDPAiMhAZvk2bDaAh-dMWmETdSvLG_cUQ4b7uIT8mBc-fOsgq5bPmqawCWsAQT5AJB-KkQKTkFDPYR8JBX_MNZEaW_WoGgKLAwYsuNhOSwrTCBuDYYi_RalLhLaWn-279CcWgJ1ttCN5g2pVDTtqRjBbk55QhORy2fLW0gEDFm0rgPR7iNZ8mFIcJD3qYUlGrebZju69iTCQz29f1hsfM0tJe_qwAY5fD_f9Qr7ZquSBxSUN8e3_CniUvRsiW1F5JfBOd8KVE-i8WkXKvlffv3tU--UvPyXE2XDvcAXrVpBL413I5xMJP28h0QPF1I3NiqJH8N0tw4y6W3e15k6ZZkGad9qnm6BzG8DMbVBW8a1HY0OKHPY1RReY8qopboL0eNVrnHsl-QHGo6lM9_wsK2vfst4wpECLtvyjmz2SxSnKDe94aoROhGmljdMsiOwKLOrK67XBdiNMpSoMn6Xq5LKgcjBH6bWIjZbWrw0YPfw9lOSsO5ntd9Njcx66pzLmwsFcWYA0vxFbRReBZRhXAaqW-ZigkdL58UGUa2gz-7w7GFfKGrjvV4bZIGxmHLsGel-vUbglR90bkQ1MEFDuqfRLVtaYm0m86qfPAFykiSxzS4sZwdekWHNDfR5cclNyloXQ1YKYPCV04nIHpoWBQh-Lqe-hFnrJP8MDIzuQbYd3PeiSkcVOjL0kIEE6PVTuPbKPgBjMHX2ZkM2iU8NLAKkYI-mXTRFPrOrglKvp90g4NyJxdE-1tJKHpph5yPWM-fu1vHaEYKxWqPN5eowZupFHXBrJTNQCVLOjmpZwIxQErioE_1sXrrXymsTAHVo0ZuQVtrOGuK_Vvk0h061uLCRJ963LAT5SpewIpD8W6X-brL5OMg&isca=1)

**Pull request merged**
