### PR TITLE
Fix upgrade test flakiness

### LINKED ISSUE #2427: Upgrade test wathola receiver reports missing event but the event was received
**Describe the bug**

In https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1417/upgrade-tests_eventing-kafka-broker_main/1552553233526820864, the reports says:

```
event #23341 should be received once, but was received 0 times
```

by downloading and viewing the [trace](https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1417/upgrade-tests_eventing-kafka-broker_main/1552553233526820864/artifacts/04056064-0e45-11ed-bb1d-ea88fc77f242/traces/events/step-23341.json) as described in https://github.com/knative/eventing/tree/main/test/upgrade#inspecting-zipkin-traces-for-undelivered-events, I see that the event was received successfully (200):

image

 **Expected behavior**

Test passes reliably.

 **To Reproduce**

Run upgrade test, in particular KafkaSource and KafkaSink continuous tests.

 **Knative release version**

`devel`

 **Additional context**

/priority important-soon

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes #2427

## Proposed Changes

- Set teardown delay to 10 seconds

### CODE REVIEW

**Comment by pierDipi** [comment]
Worked, retesting
/test upgrade-tests_eventing-kafka-broker_main

**Comment by pierDipi** [comment]
Worked, retesting
/test upgrade-tests_eventing-kafka-broker_main

**Comment by pierDipi** [comment]
```
{Failed  === RUN   TestSingleBinaryEventForChannel/KafkaChannel-messaging.knative.dev/v1beta1
    channel_single_event_helper.go:62: Run test with channel {"KafkaChannel" "messaging.knative.dev/v1beta1"}
    test_runner.go:161: Couldn't initialize clients: unable to find available namespace
    --- FAIL: TestSingleBinaryEventForChannel/KafkaChannel-messaging.knative.dev/v1beta1 (15.76s)
}
```
/test integration-tests_eventing-kafka-broker_main

**Comment by pierDipi** [comment]
Worked 2/2, retesting
/test upgrade-tests_eventing-kafka-broker_main

**Comment by aliok** [comment]
/test upgrade-tests_eventing-kafka-broker_main

3 is the charm
feel free to unhold then

**Comment by pierDipi** [comment]
> /test upgrade-tests_eventing-kafka-broker_main
> 
> 3 is the charm feel free to unhold then

:smile: it is actually 6 now https://prow.knative.dev/pr-history/?org=knative-sandbox&repo=eventing-kafka-broker&pr=2471 (the failure was my misconfiguration)

**Pull request merged**
