### PR TITLE
Remove hardcoded GOPATH from developer docs.

### PR DESCRIPTION
**Pull request by Alfusainey**
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>

## Proposed Changes

- Use `go env GOPATH` to retrieve the path to a  user's Go directory

### CODE REVIEW

**Comment by Alfusainey** [comment]
i think it will be nice if we can specify the minimum versions of the software tools required during developement (e.g `java`, `go`, `ko`, etc). this will help new contributors to know the minimum versions required to build the project

also, the link to the `knative install docs` already assumes the installation of a kubernetes cluster. so when the doc says:

> Follow an installation guide up through "Creating a Kubernetes Cluster"

this  is very confusing since creating a kubernetes cluster  is  not specified in that website. is that the linked website is recently updated?

**Comment by pierDipi** [comment]
Thank you for the PR.

/ok-to-test

---

> i think it will be nice if we can specify the minimum versions of the software tools required during developement (e.g `java`, `go`, `ko`, etc). this will help new contributors to know the minimum versions required to build the project.

This is nice to have. 
Since keeping versions in sync with the reality is hard, I would add links to the code that has that information. 
- `Java` (see https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/data-plane/pom.xml - `java.version`)
- `Go` (see https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/go.mod - `go <version>`)
- `ko` (for development we don't need a specific version)

Would you mind opening a PR for this?

---

> also, the link to the knative install docs already assumes the installation of a kubernetes cluster. so when the doc says:
> Follow an installation guide up through "Creating a Kubernetes Cluster"
> this is very confusing since creating a kubernetes cluster is not specified in that website. is it that the linked website is recently updated?

I will update that documentation with a k8s cluster installation tailored for this project. 
Would you mind opening an issue?

**Comment by Alfusainey** [comment]
> Thank you for the PR.
> 
> /ok-to-test
> 
> > i think it will be nice if we can specify the minimum versions of the software tools required during developement (e.g `java`, `go`, `ko`, etc). this will help new contributors to know the minimum versions required to build the project.
> 
> This is nice to have.
> Since keeping versions in sync with the reality is hard, I would add links to the code that has that information.
> 
>     * `Java` (see https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/data-plane/pom.xml - `java.version`)
> 
>     * `Go` (see https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/go.mod - `go <version>`)
> 
>     * `ko` (for development we don't need a specific version)
> 
> 
> Would you mind opening a PR for this?

sure

> 
> > also, the link to the knative install docs already assumes the installation of a kubernetes cluster. so when the doc says:
> > Follow an installation guide up through "Creating a Kubernetes Cluster"
> > this is very confusing since creating a kubernetes cluster is not specified in that website. is it that the linked website is recently updated?
> 
> I will update that documentation with a k8s cluster installation tailored for this project.
> Would you mind opening an issue?

create #26

**Pull request merged**
