### PR TITLE
Add linting config and fix issues.

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title. Prep work for https://github.com/knative-sandbox/.github/pull/13 to land in sandbox.

### CODE REVIEW

**Comment by pierDipi** [comment]
/hold

Methods removed are supposed to be used. (see https://github.com/knative-sandbox/eventing-kafka-broker/pull/157, and thanks for doing this)

**Comment by markusthoemmes** [comment]
@pierDipi want to keep them alive via a nolint flag then or ditch them and bring them back when the issue is worked on? :thinking: 

I suppose we can hold off of adding the linter here too if you think it'd get too much in the way of active development.

**Comment by markusthoemmes** [comment]
Nevermind, you've actually sent a PR :joy:.

**Comment by slinkydeveloper** [comment]
@markusthoemmes can you rebase on master?

**Comment by markusthoemmes** [comment]
@slinkydeveloper done!

**Review by pierDipi — APPROVED** [review]
/lgtm

Thank you!

**Pull request merged**
