### PR TITLE
Now go test GH action should collect properly the coverage

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

This should properly fix coverage collection

## Proposed Changes

- :bug: Fix coverage collection

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
/hold

https://github.com/knative/pkg/issues/2113

**Review by pierDipi — COMMENTED** [review]
I think this workflow is synced by knobots, so we need to change knobots config.

**Comment by benmoss** [comment]
What's broken about code coverage in the first place that you wanted to make this change?

**Comment by slinkydeveloper** [comment]
@benmoss answered here https://github.com/knative-sandbox/.github/pull/111

**Pull request closed without merging**
