### PR TITLE
Channel e2e tests multiarch

### LINKED ISSUE #2416: e2e tests: pre-built test utility images prevent testing on non-Intel architectures
**Describe the bug**

The e2e channel tests that are run whenever the environment variable 'EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO' is set accordingly are using pre-built Docker images (quite outdated images that haven't been updated it would seem) that are only available for platform 'amd64'. This prevents running the same tests other platforms like s390x, ppc64le, arm64 etc.

Reference:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/655216704c896d5748dc0e8b0fd733605638276d/test/scripts/first-event-delay.sh#L75

 **Expected behavior**
The e2e channel tests are running on any platform, not just Intel. This could be achieved by leveraging 'ko' to built the test images on-demand for the targeted test platform.

 **To Reproduce**
Try to run the e2e channel tests on e.g. s390x - the tests will fail as the 'heartbeat' and 'event-display' deployments will not come up properly due to image architecture mismatch.

 **Knative release version**
all (including main)

 **Additional context**
For multi-arch platform support these tests should be fixed.

### PR DESCRIPTION
**Pull request by haubenr**
Fixes #2416 

## Proposed Changes

- replace references to pre-built Docker images with images built by 'ko' ad-hoc (honoring the KO_FLAGS environment variable present in the prow test container)

### CODE REVIEW

**Comment by pierDipi** [comment]
Thanks!

/ok-to-test

**Comment by haubenr** [comment]
Test environment issues? 
image

**Pull request merged**
