### PR TITLE
enable code coverage

### PR DESCRIPTION
**Pull request by n3wscott**
Related to https://github.com/knative-sandbox/.github/pull/20
/cc @mattmoor

### CODE REVIEW

**Comment by pierDipi** [comment]
Cool! I'll adjust ignore patterns in a new PR.

/assign @slinkydeveloper

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by slinkydeveloper** [comment]
I wonder if we can enable this for java too :thinking:

**Comment by slinkydeveloper** [comment]
I see they support it in the languages, it requires a maven plugin https://docs.codecov.io/docs/supported-languages

**Comment by pierDipi** [comment]
We can do it ourselves later.

**Pull request merged**
