### PR TITLE
Now verify codegen GH action should be happy

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by matzew — APPROVED** [review]

**Review by devguyio — APPROVED** [review]

**Comment by slinkydeveloper** [comment]
I guess I need your approval @pierDipi :smile:

**Review by pierDipi — APPROVED** [review]
Folks, feel free to add you to the approver list.

**Comment by pierDipi** [comment]
```
Failed to configure pod "recordevents-pod": Operation cannot be fulfilled on resourcequotas "gke-resource-quotas": StorageError: invalid object
```
/retest

**Pull request merged**
