### PR TITLE
Use WaitForPodRunning instead of WaitForResourceReady

### PR DESCRIPTION
**Pull request by pierDipi**
Try to address:
- #179
- #174
- #172
- #171

Use the specific WaitForPodRunning instead of WaitForResourceReady

## Proposed Changes

- Use WaitForPodRunning instead of WaitForResourceReady

### CODE REVIEW

**Comment by pierDipi** [comment]
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
2/2
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

/assign @slinkydeveloper

**Comment by slinkydeveloper** [comment]
@pierDipi since this tests was copied from eventing, can you propose the fix there too?

**Comment by pierDipi** [comment]
@slinkydeveloper I planned to monitor them in continuous testing, and then propose it so that I'm sure what I'm proposing is the right thing to do, does that seem reasonable to you?

**Comment by pierDipi** [comment]
3/3
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
4/4
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
5/5
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Pull request merged**
