### PR TITLE
Remove vendoring of knative.dev/eventing-kafka/test/rekt

### PR DESCRIPTION
**Pull request by creydr**
[SRVKE-1370](https://issues.redhat.com/browse/SRVKE-1370)

## Proposed Changes

- :broom: Remove dependency to `knative.dev/eventing-kafka/test/rekt` by including the sources in the broker repo itself

### CODE REVIEW

**Comment by matzew** [comment]
Thanks for this!

One thought: Instead of putting it on `test/rekt` (like the legacy repo had it), why not stashing it onto `e2e_new_channel`?

For the broker, we do have the `features` and `resources` folder there:
- https://github.com/creydr/knative-eventing-kafka-broker/tree/move-eventing-kafka-test-rekt-to-broker/test/e2e_new/features
- https://github.com/creydr/knative-eventing-kafka-broker/tree/move-eventing-kafka-test-rekt-to-broker/test/e2e_new/resources

OR: we move (in a separate PR), the content from `test/e2e_new` to the `test/rekt` ? 

Not sure

**Comment by creydr** [comment]
> One thought: Instead of putting it on `test/rekt` (like the legacy repo had it), why not stashing it onto `e2e_new_channel`?
> 
> For the broker, we do have the `features` and `resources` folder there:
> 
> * https://github.com/creydr/knative-eventing-kafka-broker/tree/move-eventing-kafka-test-rekt-to-broker/test/e2e_new/features
> * https://github.com/creydr/knative-eventing-kafka-broker/tree/move-eventing-kafka-test-rekt-to-broker/test/e2e_new/resources
> 
> OR: we move (in a separate PR), the content from `test/e2e_new` to the `test/rekt` ?
> 
> Not sure

Hi @matzew,
thanks for checking on this. Good point... I don't have a hard opinion on this, but moving it into `e2e_new_channel` and having something similar in `e2e_new` feels duplicate if they belong together. So I like the 2nd idea of moving `test/e2e_new` to `test/rekt` a bit more. But these are just my bits on it...
@pierDipi @aliok any opinions?

**Comment by matzew** [comment]
> So I like the 2nd idea of moving `test/e2e_new` to `test/rekt` a bit more. But these are just my bits on it...

Sounds good to me. This is something we can (and should) do separately, to not bloat this PR

**Comment by creydr** [comment]
> This is something we can (and should) do separately, to not bloat this PR

Agree. I'll follow up on this

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
