### PR TITLE
Add tests for previous versions of Eventing

### PR DESCRIPTION
**Pull request by pierDipi**
This PR starts running E2E tests using previous versions of Eventing.

## Proposed Changes

- Add tests for previous versions of eventing

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
I would love to wait for it and merge it after the release, since it might introduce additional CI instability

/hold

**Comment by pierDipi** [comment]
This runs in GH Actions only, the problem we have is only with `sacura`, anyway no strong opinion.

**Comment by slinkydeveloper** [comment]
I know it runs on gh actions, but i don't want to let the repo looks like unstable

**Comment by pierDipi** [comment]
Can we merge this now?

**Review by slinkydeveloper — APPROVED** [review]

**Pull request merged**
