### PR TITLE
Keep protobuf generated code in repository

### LINKED ISSUE #22: Keep protobuf generated code in repository
**Problem**
In order to get started contributing a developer needs to generate code. 
We can keep generated code by `protoc` in the repository. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributor

**Exit Criteria**
- Get rid of `hack/dev_data_plane_setup.sh`
- Add `hack/update-codegen.sh`
- Add `hack/verify-codegen.sh`
- Remove Git ignore rules for generated code. (see `data-plane/.gitignore`)

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

/assign

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes #22 

## Proposed Changes

- Add generated `data-plane/generated` and `control-plane/pkg/core/config`
- Remove code generation section from development process docs
- Remove protobuf code generation from presubmit-tests.sh
- Remove `hack/dev_data_plane_setup.sh` (related #20)
- Add verify-codegen.sh and update-codegen.sh

### CODE REVIEW

**Comment by pierDipi** [comment]
Prow were down.
/cc slinkydeveloper

**Comment by slinkydeveloper** [comment]
Should this PR contain the java generated code too?

**Comment by pierDipi** [comment]
This https://github.com/knative-sandbox/eventing-kafka-broker/pull/23/files#diff-b14aa3ac15a8d21b70c96c6c9386bd39?

**Comment by slinkydeveloper** [comment]
Ah i missed it :smile:

**Pull request merged**
