### PR TITLE
[WIP] Try increasing MaxNamespaceSkip and more logging

### PR DESCRIPTION
**Pull request by mgencur**
Fixes #

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
Different issue, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
Different flake
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by mgencur** [comment]
hi @pierDipi , increasing the number to 100 worked several times in a row. I think it will fix the issue because I can see in the logs that the latest namespace is `eventing-e2e69`.  I can't send the PR today to Eventing, though. If you can do it that would be great. Thanks

**Comment by pierDipi** [comment]
Sure, I'll do that later today, thanks!

**Pull request closed without merging**
