### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- as per title, but let's see.

Part of the _actual_ fix was, remove dependencies, that have been deleted or moved:
```
go: finding module for package knative.dev/eventing/test/rekt/resources/svc
go: finding module for package knative.dev/eventing/test/test_images/heartbeats
go: found knative.dev/eventing/test/test_images/heartbeats in knative.dev/eventing v0.36.7
go: found knative.dev/eventing/test/rekt/resources/svc in knative.dev/eventing v0.36.7
```

Change for that was in:
* [hack/tools.go](https://github.com/knative-sandbox/eventing-kafka-broker/pull/3041/files#diff-c70c0ccc1e4ba2d6da1d6c59877e3600c6771f133dec670df485e23fde6cb795)
* [test/e2e_new_channel/tracing_test.go](https://github.com/knative-sandbox/eventing-kafka-broker/pull/3041/files#diff-2d66718964aa141e3cd7bb2916be23d2fc8ba3e563fe8d2ff44dfeb537d1ede7)

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
Locally, with this branch/pr, I see:

 ```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    3m41s                default-scheduler  Successfully assigned knative-eventing/kafka-source-dispatcher-0 to kind-control-plane
  Warning  FailedMount  98s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[contract-resources], unattached volumes=[config-tracing kube-api-access-rj52h config-kafka-source-data-plane contract-resources cache kafka-config-logging]: timed out waiting for the condition
  Warning  FailedMount  94s (x9 over 3m41s)  kubelet            MountVolume.SetUp failed for volume "contract-resources" : configmap "kafka-source-dispatcher-0" not found
```

**Comment by matzew** [comment]
```
Error: error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
2023/04/18 14:26:52 error during command execution:error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
error: no objects passed to apply
Error: error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
2023/04/18 14:26:52 error during command execution:error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
error: no objects passed to apply
Error: error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
2023/04/18 14:26:53 error during command execution:error processing import paths in "-": error resolving image references: found strict reference but ko://knative.dev/eventing/test/test_images/heartbeats is not a valid import path: importpath is not `package main`
error: no objects passed to apply
E````

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
