### PR TITLE
Pin sarama version to v1.29.1

### PR DESCRIPTION
**Pull request by odacremolbap**
Fixes https://github.com/knative-sandbox/eventing-kafka-broker/issues/1421

Workarond sticks to Samara v1.29.1 so that Knative tests do not fail.
This is not intended to be permanent and should be removed when a PR akin to [this](https://github.com/knative-sandbox/eventing-kafka/pull/975) gets merged.

There is also an update of the kn/hack repo which I don't think is strictly needed here, but will resolve tags from `knative-v1.0.0` and on for any test that needs it.

## Proposed Changes

- Pin the samara version to v1.29.1. Will need to be unpinned when it is upgraded at this repo.

### CODE REVIEW

**Comment by pierDipi** [comment]
Hi @odacremolbap, I sent a PR to bump Sarama to 1.30 https://github.com/knative-sandbox/eventing-kafka-broker/pull/1435

**Comment by odacremolbap** [comment]
Thanks so much @pierDipi 
Closing this.

**Pull request closed without merging**
