### PR TITLE
[WIP] Remove duplicated log lines in CI artifacts

### PR DESCRIPTION
**Pull request by pierDipi**
There are duplicated log lines in CI artifacts in our components because they are sent to multiple loggers.

```
{"@timestamp":"2020-11-10T01:41:06.832Z","@version":"1","message":"record match filtering topic=knative-broker-sacura-broker partition=6 offset=11616","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.ConsumerRecordHandler","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":6,"offset":11616,"event":{"data":"ImhlbGxvIg==","id":"85cb8b97-629e-4fbf-ae4d-22915a2261b1","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":{"offset":{"totalSeconds":0,"id":"Z","rules":{"transitions":[],"transitionRules":[],"fixedOffset":true}},"nano":780000000,"year":2020,"monthValue":3,"dayOfMonth":21,"hour":12,"minute":34,"second":56,"month":"MARCH","dayOfWeek":"SATURDAY","dayOfYear":81},"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2020-11-10T01:41:06.832Z","@version":"1","message":"handling record topic=knative-broker-sacura-broker partition=6 offset=11617","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.ConsumerRecordHandler","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":6,"offset":11617,"event":{"data":"ImhlbGxvIg==","id":"6be42d92-0ee0-4067-acbd-992e8a3f039a","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":{"offset":{"totalSeconds":0,"id":"Z","rules":{"transitions":[],"transitionRules":[],"fixedOffset":true}},"nano":780000000,"year":2020,"monthValue":3,"dayOfMonth":21,"hour":12,"minute":34,"second":56,"month":"MARCH","dayOfWeek":"SATURDAY","dayOfYear":81},"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2020-11-10T01:41:06.832Z","@version":"1","message":"handling record topic=knative-broker-sacura-broker partition=6 offset=11617","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.ConsumerRecordHandler","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":6,"offset":11617,"event":{"data":"ImhlbGxvIg==","id":"6be42d92-0ee0-4067-acbd-992e8a3f039a","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":{"offset":{"totalSeconds":0,"id":"Z","rules":{"transitions":[],"transitionRules":[],"fixedOffset":true}},"nano":780000000,"year":2020,"monthValue":3,"dayOfMonth":21,"hour":12,"minute":34,"second":56,"month":"MARCH","dayOfWeek":"SATURDAY","dayOfYear":81},"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2020-11-10T01:41:06.832Z","@version":"1","message":"record match filtering topic=knative-broker-sacura-broker partition=6 offset=11617","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.ConsumerRecordHandler","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":6,"offset":11617,"event":{"data":"ImhlbGxvIg==","id":"6be42d92-0ee0-4067-acbd-992e8a3f039a","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":{"offset":{"totalSeconds":0,"id":"Z","rules":{"transitions":[],"transitionRules":[],"fixedOffset":true}},"nano":780000000,"year":2020,"monthValue":3,"dayOfMonth":21,"hour":12,"minute":34,"second":56,"month":"MARCH","dayOfWeek":"SATURDAY","dayOfYear":81},"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
```

## Proposed Changes

- Remove duplicated log lines in CI artifacts

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@pierDipi Can we merge this one?

**Comment by pierDipi** [comment]
I think it doesn't work :(

**Pull request closed without merging**
