### PR TITLE
Do not copy locks

### LINKED ISSUE #2634: Error: copylocks: Del passes lock by value: knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/broker.Counter contains sync.RWMutex
**Describe the bug**

```
Error: copylocks: Inc passes lock by value: knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/broker.Counter contains sync.RWMutex (govet)
  Error: copylocks: Del passes lock by value: knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/broker.Counter contains sync.RWMutex (govet)
```

See https://github.com/knative-sandbox/eventing-kafka-broker/runs/8268828650?check_suite_focus=true 

 **Expected behavior**

No linting errors.

 **To Reproduce**

Run lint CI job

 **Knative release version**
`main` + `backports`

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes #2634

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Cherry-pick of this is included in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2629

**Pull request merged**
