### PR TITLE
[WIP] Add script template for rekt tests, which will be used in Prow job

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Add script template for rekt tests, which will be used in Prow job
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
We're using the `e2e_new` directory and the `reconciler-tests` job for rekt tests

**Comment by aliok** [comment]
@pierDipi 

Hmm, ok, maybe it is a better idea to just run the knative/eventing's Rekt tests with KafkaChannel in e2e_new

**Comment by pierDipi** [comment]
> @pierDipi
> 
> Hmm, ok, maybe it is a better idea to just run the knative/eventing's Rekt tests with KafkaChannel in e2e_new

I agree.

Perhaps, eventually, we might want to rename `e2e_new` to `rekt` for consistency with the eventing

**Comment by aliok** [comment]
/close

I moved the rekt tests under `e2e_new`

**Pull request closed without merging**
