### PR TITLE
update to pkg KubeTest

### PR DESCRIPTION
**Pull request by n3wscott**

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]
/lgtm

**Comment by n3wscott** [comment]
Looks like there was a breaking change in eventing too.. fixed that?

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Comment by n3wscott** [comment]
/retest

hmmm

```
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @4c98385c
```

**Comment by slinkydeveloper** [comment]
> java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @4c98385c

Funky warning, u know java unsafe :laughing:

**Pull request merged**
