### PR TITLE
Drop Kubernetes 1.19 and add 1.22

### PR DESCRIPTION
**Pull request by pierDipi**
## Proposed Changes

- Drop k8s 1.19 and add 1.22 (this blocks https://github.com/knative-sandbox/eventing-kafka-broker/pull/1240)
- Drop obsolete versions of eventing (this needs automation if we want to keep testing previous versions)
- Update eventing-latest manifests (since automation is broker, fix in https://github.com/knative-sandbox/knobots/pull/108)

**Release Note**

```release-note
Drop support for Kubernetes 1.19.
```

/kind removal
/assign @matzew

### CODE REVIEW

**Comment by pierDipi** [comment]
Blocked by https://github.com/knative-sandbox/knobots/pull/108

**Comment by ZhiminXiang** [comment]
/lgtm
/hold

Feel free to unhold it if anyone from eventing side feels it is good to go.

**Pull request merged**
