### PR TITLE
Add webhook Service Monitor

### PR DESCRIPTION
**Pull request by pierDipi**
- Add Service Monitor for `kafka-webhook-eventing`
- Add metrics port to `kafka-webhook-eventing` Service

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
cc @skonto

**Comment by skonto** [comment]
LGTM. I verified that metrics are exposed end-to-end.
image
image

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
