### PR TITLE
Removed test_images

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Part of https://github.com/knative/eventing/pull/4358

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
```
 2020/10/20 18:02:23 Unexpected error running "go build": exit status 1
vendor/github.com/google/go-github/v27/github/git_commits.go:16:2: cannot find package "." in:
	/home/prow/go/src/knative.dev/eventing-kafka-broker/vendor/golang.org/x/crypto/openpgp
2020/10/20 18:02:23 Unexpected error running "go build": signal: killed
2020/10/20 18:02:23 Unexpected error running "go build": signal: killed
2020/10/20 18:02:23 Unexpected error running "go build": signal: killed
2020/10/20 18:02:23 Unexpected error running "go build": signal: killed
```

Funky

**Comment by slinkydeveloper** [comment]
I can build images locally....

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
