### PR TITLE
[1.2] Do not delete finalizer until the probe returns status not ready

### PR DESCRIPTION
**Pull request by pierDipi**
This PR fixes a problem that we have since we were deleting the
finalizer without deleting the topic accordingly since we were
returning nil in `FinalizeKind` which deletes the finalizer from
the resource.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
After we merge this PR, I'll ask someone to start the dot release job for 1.2 to unblock other PRs that can't be merged due to the upgrade test failure.

Can you take a look, please?

/assign @aliok @devguyio @matzew

**Comment by pierDipi** [comment]
```
           {
            "type": "Ready",
            "status": "False",
            "lastProbeTime": null,
            "lastTransitionTime": "2022-01-26T15:05:34Z",
            "reason": "ContainersNotReady",
            "message": "containers with unready status: [eventshub]"
           },
```

**Comment by pierDipi** [comment]
This works now! :partying_face:

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
