### PR TITLE
[clean up] Removing config map finalizer left overs

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

-  addressing todo and remove remove cm finalizer, since it was already released

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
looking at the isse

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
