### PR TITLE
Moving hardcoded values to controller environment variables, and config maps ready (Consumer Scheduling and Scaling)

### PR DESCRIPTION
**Pull request by aavarghese**
Signed-off-by: aavarghese <avarghese@us.ibm.com>

Part of #1537

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by aavarghese** [comment]
@pierDipi sorry!! There was a newline lint err. Can you lgtm again please?

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by aavarghese** [comment]
@pierDipi I missed to specify the seconds unit for refresh period. Oops. When you get a chance, one more time please? :)

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
