### PR TITLE
use builtin MacOS sed in data-plane script

### LINKED ISSUE #2137: Build fails with sed error in MacOS
**Describe the bug**
Build fails with sed error in MacOS

Example

```
============================
==== Fri Apr 29 06:35:03 PDT 2022
============================
Dispatcher image ---> docker.io/aslom/knative-kafka-broker-dispatcher:1728ce5c5b71ef0272b48fc61a5ab0363b72ad6f4049c0d3ed4be118b4502385
Receiver image   ---> docker.io/aslom/knative-kafka-broker-receiver:6b977181a9e1a32b00c8780bebf194d62d4dcd870edce52025ce1bd55a914a87
sed: 1: "eventing-kafka-source.yaml": invalid command code e
ERROR: Failed to set up data plane components
***************************************
***         E2E TEST FAILED         ***
***    Start of information dump    ***
***************************************
```

 **Expected behavior**
Build works

 **To Reproduce**
On MacOS

```
 ./hack/run.sh deploy 
```

 **Knative release version**
1.4

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by aslom**
Fixes #2137

Build ./hack/run.sh fails with sed error in MacOS 

## Proposed Changes
- use builtin MacOS sed in data-plane script - that should *always* work even in gsed is not installed

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
I prefer using the other approach [1] and require to use GNU toolchain since that's what other Knative projects are using:

[1]
https://github.com/knative-sandbox/eventing-kafka-broker/issues/2137#issuecomment-1114610686

**Comment by aslom** [comment]
@pierDipi implemented approach with aliased gsed

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
