### PR TITLE
Implemented OrderedConsumerVerticle

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Part of #589

## Proposed Changes

- Implemented `OrderedConsumerVerticle`
- Refactored `dev.knative.eventing.kafka.broker.dispatcher.consumer.impl` tests to share test code

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Control plane / API stuff in another PR?

/lgtm

**Comment by pierDipi** [comment]
Whoops, there are conflicts.

**Comment by slinkydeveloper** [comment]
> Control plane / API stuff in another PR?

Sure, I want to do the wire up in another PR.

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
Can you open an issue to track control plane and API changes?

**Comment by slinkydeveloper** [comment]
@pierDipi i'll add to the original issue

**Pull request merged**
