### PR TITLE
Delete global resources during KafkaSource migration

### PR DESCRIPTION
**Pull request by pierDipi**
- Delete mutatingwebhookconfigurations.admissionregistration.k8s.io/defaulting.webhook.kafka.sources.knative.dev
- Delete validatingwebhookconfigurations.admissionregistration.k8s.io/validation.webhook.kafka.sources.knative.dev
- Delete validatingwebhookconfigurations.admissionregistration.k8s.io/config.webhook.kafka.sources.knative.dev
- Delete service knative-eventing/kafka-source-webhook
- Delete Service knative-eventing/kafka-controller
- Delete deployment.apps/kafka-controller-manager
- Delete ClusterRoleBinding/eventing-sources-kafka-controller
- Delete ClusterRoleBinding/eventing-sources-kafka-controller-addressable-resolver
- Delete ClusterRole/eventing-sources-kafka-controller
- Delete ServiceAccount knative-eventing/kafka-controller-manager
- Delete ConfigMap knative-eventing/config-kafka-source-defaults
- Delete Secret knative-eventing/kafka-source-webhook-certs

Based on https://github.com/knative-sandbox/eventing-kafka-broker/pull/1889

## Proposed Changes

- Delete global resources during KafkaSource migration

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
/retest-required

Webhook EOF pkg issue:
```
    kafka_sink.go:92: 
        	Error Trace:	kafka_sink.go:92
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Internal error occurred: failed calling webhook \"validation.webhook.kafka.eventing.knative.dev\": failed to call webhook: Post \"https://kafka-webhook-eventing.knative-eventing.svc:443/resource-validation?timeout=2s\": EOF", Reason:"InternalError", Details:(*v1.StatusDetails)(0xc00037c540), Code:500}}
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
