### PR TITLE
Remove `ConsumerRebalanceListener` from `ConsumerVerticleContext`

### PR DESCRIPTION
**Pull request by debasishbsws**
A clean conflict-free PR of #3195

## Proposed Changes

- Put the `ConsumerRebalanceListener` into `ConsumerVerticle`

### CODE REVIEW

**Comment by debasishbsws** [comment]
@pierDipi 
"Did you consider passing to the consumer verticle the rebalance listener instead of passing all revoke handlers?

 consumerVerticle.setRebalanceListener(createRebalanceListener(partitionRevokedHandlers));
That would decouple the consumer verticle from the rebalance logic, in my opinion, creating and coordinating the build of the rebalance listener is more a responsibility of the builder rather than a responsibility of the consumer verticle (consumer verticle is responsible for the lifecycle of the consumer)"(https://github.com/knative-sandbox/eventing-kafka-broker/pull/3195/files#r1259704553)

In this approach, some tests are failing as the consumerVerticleListener is not getting initialised.
I can put a check like
```java
protected ConsumerRebalanceListener getConsumerRebalanceListener() {
        if(consumerRebalanceListener != null){
            return consumerRebalanceListener;
        }
        return new ConsumerRebalanceListener() {
            @Override
            public void onPartitionsRevoked(final Collection<TopicPartition> partitions) {
                getPartitionRevokedHandler().partitionRevoked(partitions).onComplete(
                        r -> logger.info("Partitions revoked {}", consumerVerticleContext.getLoggingKeyValue()));
            }

            @Override
            public void onPartitionsAssigned(final Collection<TopicPartition> partitions) {
                logger.info("Partitions assigned {}", consumerVerticleContext.getLoggingKeyValue());
            }
        };
    }
```
But I think it is like same as Building the ConsumerRebalanceListener inside it.
OR
I can create a new ConsumerRebalanceListenerImpl and move the logic there as I Previously did in Old PR old commit https://github.com/knative-sandbox/eventing-kafka-broker/pull/3195/commits/aa9b1397f78e8656bf93c32efb8ea19f897447ab

**Comment by pierDipi** [comment]
> 
> In this approach, some tests are failing as the consumerVerticleListener is not getting initialised. I can put a check like
> 
> ```java
> protected ConsumerRebalanceListener getConsumerRebalanceListener() {
>         if(consumerRebalanceListener != null){
>             return consumerRebalanceListener;
>         }
>         return new ConsumerRebalanceListener() {
>             @Override
>             public void onPartitionsRevoked(final Collection<TopicPartition> partitions) {
>                 getPartitionRevokedHandler().partitionRevoked(partitions).onComplete(
>                         r -> logger.info("Partitions revoked {}", consumerVerticleContext.getLoggingKeyValue()));
>             }
> 
>             @Override
>             public void onPartitionsAssigned(final Collection<TopicPartition> partitions) {
>                 logger.info("Partitions assigned {}", consumerVerticleContext.getLoggingKeyValue());
>             }
>         };
>     }
> ```
> 
> But I think it is like same as Building the ConsumerRebalanceListener inside it. OR I can create a new ConsumerRebalanceListenerImpl and move the logic there to decouple the consumer verticle from the rebalance logic as I Previously did in Old PR old commit [aa9b139](https://github.com/knative-sandbox/eventing-kafka-broker/commit/aa9b1397f78e8656bf93c32efb8ea19f897447ab)

I didn't get what's the problem, can you expand a bit more?

**Comment by debasishbsws** [comment]
I have moved the ConsumerRebalanceLitener creation Logic out from the ConsumerVerticle and use `consumerVerticle.setRebalanceListener(... );` instead. But now ConsumerRebalanceLitener is not getting initialised while running some tests like OrderedConsumerVeticleTest, UnordereConsumerVerticleTest.
So I was asking that to resolve that I can put a condition like if the ConsumerRebalanceLitener is null then create a new one and return it to make sure we never get a null.

**Comment by debasishbsws** [comment]
Oh wait I can put
```java
consumerVerticle.setRebalanceListener(new ConsumerRebalanceListener() {....})
```
into the test.

**Pull request merged**
