### PR TITLE
Bump Sarama from 1.27.0 to 1.27.2

### LINKED ISSUE #278: Bump Sarama from 1.27.0 to 1.27.2
**Problem**

We need to bump the Sarama library, see release notes: https://github.com/Shopify/sarama/releases/tag/v1.27.2

**Exit Criteria**
Bump Sarama from 1.27.0 to 1.27.2

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

There are some breaking changes even if it's a patch release.

/kind feature-request
/good-first-issue

### PR DESCRIPTION
**Pull request by sheetalsingala**
Fixes #278 

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
Thanks! You need to run `./hack/udpate-deps.sh` to fix CI errors.

**Comment by pierDipi** [comment]
Hi @sheetalsingala, would you mind running `./hack/udpate-deps.sh` to fix CI errors, so that we can merge this PR?

**Comment by sheetalsingala** [comment]
Could you help me resolve issues related to the failed checks? @pierDipi

**Comment by pierDipi** [comment]
Have you run `./hack/udpate-deps.sh` (https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/hack/update-deps.sh.)? If I check out your PR I get a non-empty diff by running that script.

**Comment by slinkydeveloper** [comment]
Any updates on this PR?

**Comment by sheetalsingala** [comment]
> Any updates on this PR?

Opened #565 
Will close this

**Pull request closed without merging**
