### PR TITLE
[WIP] Port sink delete config map test

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Part of #1077

## Proposed Changes

- :broom: Port sink delete config map test to e2e_new

### CODE REVIEW

**Comment by pierDipi** [comment]
```
Found diffs in: third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
fatal: ambiguous argument 'third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: Please run ./hack/update-codegen.sh.

knative-sandbox/eventing-kafka-broker is out of date. Please run hack/update-codegen.sh
```

**Comment by slinkydeveloper** [comment]
Depends on #1085

**Comment by matzew** [comment]
@pierDipi  should we close?

**Pull request closed without merging**
