### PR TITLE
Minor fix for missing allowed key type

### PR DESCRIPTION
**Pull request by aavarghese**
Signed-off-by: aavarghese <avarghese@us.ibm.com>

Related to #2244 

Fixes a problem in #2219

Part of #1537

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
/hold

actually, can't we just use https://github.com/knative-sandbox/eventing-kafka/blob/main/pkg/apis/sources/v1beta1/kafka_types.go#L103

**Comment by aavarghese** [comment]
> actually, can't we just use https://github.com/knative-sandbox/eventing-kafka/blob/main/pkg/apis/sources/v1beta1/kafka_types.go#L103

@matzew yeah, we should. Made that change in a new commit. Thanks!

**Review by pierDipi — APPROVED** [review]
Thank you!

/lgtm
/approve

**Pull request merged**
