### PR TITLE
Bump k8s versions in KinD workflows and remove verbose logging

### LINKED ISSUE #1067: Drop verbose logging in GitHub Actions
**Problem**

Going through logs to find a failed test in GH actions is painful since there are all logs even of succeeded tests, I think we shouldn't use the `-v` flag in there.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributor and Maintainer

**Exit Criteria**
Failed tests are easy to discover.

**Additional context (optional)**
- See any recent periodic failed action 

/good-first-issue

### PR DESCRIPTION
**Pull request by pierDipi**
Bump k8s versions to the latest 2 versions.

Drop verbose logging since doing through logs to 
find a failed test in GH actions is painful since 
there are all logs even of succeeded tests.

Fixes #1067

### CODE REVIEW

**Comment by pierDipi** [comment]
Actually, 
/hold

This seeems to break these tests: `./third_party/eventing-latest/, ./test/e2e_new)`

**Comment by aliok** [comment]
> This seeems to break these tests: ./third_party/eventing-latest/, ./test/e2e_new)

That's strange

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
