### PR TITLE
[release-0.21] Backport SASL/PLAIN fixes

### PR DESCRIPTION
**Pull request by pierDipi**
Backport #855 and #840

## Proposed Changes

- Allow SASL Mechanism to be equal to "PLAIN"

**Release Note**

```release-note
Support SASL mechanism PLAIN.
```

/kind bug

### CODE REVIEW

**Review by antoineco — APPROVED** [review]

**Comment by antoineco** [comment]
@googlebot I consent.

**Comment by slinkydeveloper** [comment]
Is this ready to be merged?

**Comment by pierDipi** [comment]
Yes, it is!

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

**Pull request merged**
