### PR TITLE
Going w/ Apache Kafka 3.3.2

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

- after strimzi bump, going with Kafkas 3.3.2

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
/assign @creydr 
please take a look (tests are passing)

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
