### PR TITLE
Handle host headers in dataplane for identification of channel instances

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Handle host headers in dataplane for identification of channel instances
- Needed to change the proto definition, but it is backwards compatible. See https://github.com/aliok/proto-experiments?
- Logic is like this:
  - If path is defined for the ingress, use that as the identification information and ignore the hostname
  - If hostname is defined for the ingress, use that as the identification information unless there's a path defined

**Release Note**

```release-note
- :gift: Handle host headers in dataplane for identification of channel instances
```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
Created instead of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1985

**Comment by aliok** [comment]
cc @pierDipi

**Comment by aliok** [comment]
/retest

```
Creating cluster e2e-cls-qoxagyct in us-east1...
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2022-03-09T21:33:26Z"}
```

**Comment by devguyio** [comment]
I am gonna take the liberty of holding this until #1922 goes in, there's a possibility of a conflict here because of contract changes and we've been working for a while to have #1922 in. 

/hold

**Comment by aliok** [comment]
/unhold

https://github.com/knative-sandbox/eventing-kafka-broker/pull/1922 is merged

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
