### PR TITLE
[master] Update GitHub Actions

### PR DESCRIPTION
**Pull request by mattmoor**
Copied from `https://github.com/knative-sandbox/.github/tree/master/workflow-templates`.
/assign slinkydeveloper
/cc slinkydeveloper

### CODE REVIEW

**Comment by mattmoor** [comment]
/hold

@slinkydeveloper Can you confirm that this doesn't screw things up?

**Comment by slinkydeveloper** [comment]
@mattmoor it adds the _Test_ task again which is redundant. Let me try if a separate unit test script it's ok for codecov

**Comment by slinkydeveloper** [comment]
Seems like codecov doesn't like 2 reports for the same PR https://github.com/knative-sandbox/eventing-kafka-broker/pull/199 one will exclude the other

**Comment by pierDipi** [comment]
I'll investigate how to merge two reports using 2 different actions.
I'm merging https://github.com/knative-sandbox/eventing-kafka-broker/pull/206 since it's the most recent one.
/close

**Pull request closed without merging**
