### PR TITLE
Migrate `TestEventTransformationForTriggerV1BrokerV1` broker e2e test to rekt test framework

### PR DESCRIPTION
**Pull request by creydr**
As per title

### CODE REVIEW

**Comment by creydr** [comment]
@pierDipi @matzew per the discussions in https://cloud-native.slack.com/archives/C04LMU33V1S/p1677752924526809: Does it make sense in your opinion to have such a test in EKB? Same applies probably to https://github.com/knative-sandbox/eventing-kafka-broker/pull/2996.

**Comment by pierDipi** [comment]
It does, why not?

I imaging that this test will use:
- Kafka broker for broker
- KafkaChannel for channel

right?

**Comment by creydr** [comment]
```
    "message": "unable to track changes to the backing Channel: inmemorychannels.messaging.knative.dev is forbidden: User \"system:serviceaccount:knative-eventing:eventing-controller\" cannot list resource \"inmemorychannels\" in API group \"messaging.knative.dev\" at the cluster scope",
```
--> 168d9d8

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
