### PR TITLE
Bump Strimzi from 0.21 to 0.23.0

### PR DESCRIPTION
**Pull request by pierDipi**
- Run `hack/update-strimzi.sh`
- Follow instructions of the script
- Bump resource versions from v1beta1 to v1beta2

## Proposed Changes

- Bump Strimzi from 0.21 to 0.23.0

### CODE REVIEW

**Comment by pierDipi** [comment]
```
The CustomResourceDefinition "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by slinkydeveloper** [comment]
@pierDipi https://github.com/strimzi/strimzi-kafka-operator/issues/4589

**Comment by pierDipi** [comment]
I'm gonna drop a version from the
CRD

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

**Pull request merged**
