### PR TITLE
Add release notes generator script

### PR DESCRIPTION
**Pull request by pierDipi**
This PR adds a `release-notes.sh` script to generate release notes
and documents how to use it.

## Proposed Changes

- Add release notes generator script

**Release Note**

```release-note
 🎁 Add new feature
- release leads or contributors can generate release notes using the `./hack/release-notes.sh` script.
```

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@n3wscott can you check out this one?

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
