### PR TITLE
Bump Go from 1.14 to 1.15

### PR DESCRIPTION
**Pull request by pierDipi**
## Proposed Changes
 
- Bump Go from 1.14 to 1.15
- Run `./hack/update-codegen.sh`

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@pierDipi Should we wait for eventing to use go 1.15 too? https://github.com/knative/eventing/blob/master/go.mod#L3

**Comment by pierDipi** [comment]
I'm fine with either way.

**Comment by slinkydeveloper** [comment]
Then let's wait for it

/hold

**Comment by pierDipi** [comment]
Working on an automatic bump for all Knative: https://github.com/knative/test-infra/issues/2149

**Pull request closed without merging**
