### PR TITLE
Pass EventTypeAutoCreate enabled flag to the data plane

### LINKED ISSUE #3220: Pass EventTypeAutoCreation flag to the Data Plane
**Problem**
Before we can work on #3174 or #3181, we need to pass the EventTypeAutoCreation flag to the data plane.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes #3220 

## Proposed Changes

- Add the feature flag to the Ingress contract
- In each reconcile loop where we set the Ingress contract, set the feature flag

### CODE REVIEW

**Comment by Leo6Leo** [comment]
https://github.com/Leo6Leo/eventing-kafka-broker/blob/32dfed583ceb02c4fa1581b3bffab07d6ec0e7d6/data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java#L436

Should the test here also need to be modified? @Cali0707

**Comment by Cali0707** [comment]
> https://github.com/Leo6Leo/eventing-kafka-broker/blob/32dfed583ceb02c4fa1581b3bffab07d6ec0e7d6/data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java#L436
> 
> Should the test here also need to be modified? @Cali0707

@Leo6Leo I don't think so? This PR is just passing the flag into the data plane, not updating the code anywhere to use it.

@pierDipi WDYT?

**Review by pierDipi — APPROVED** [review]
As long as we keep in mind that we need to add tests and we do that in a follow up this is fine

/lgtm
/approve

**Pull request merged**
