### PR TITLE
Prober targets service instead of pods directly

### LINKED ISSUE #2107: Simple Broker does not become Ready, 502
Hi all, we have a wierd issue with a simple broker not becoming ready:

```
kn broker list
NAME                             URL   AGE   CONDITIONS   READY   REASON
onboarding-ci-kn-kafka-cluster         13m   4 OK / 7     False   ProbeStatus : status: NotReady
```

Looking at the logs from kafka-controller  we see that the Probe fails due to bad gateway 502:

```
kafka-controller-7bc844bb6b-x4frd controller {"level":"debug","ts":"2022-04-20T11:19:23.200Z","logger":"kafka-broker-controller","caller":"broker/broker.go:223","msg":"Updated dispatcher pod annotation","knative.dev/pod":"kafka-controller-7bc844bb6b-x4frd","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.broker.Reconciler","knative.dev/kind":"eventing.knative.dev.Broker","knative.dev/traceid":"eae1957d-361e-4364-a22b-afa2af7241a2","knative.dev/key":"knative-eventing/onboarding-ci-kn-kafka-cluster","action":"reconcile","uuid":"88c7538e-5722-4d83-88ea-bdf01191af7d"}
kafka-controller-7bc844bb6b-x4frd controller {"level":"info","ts":"2022-04-20T11:19:23.200Z","logger":"kafka-broker-controller","caller":"controller/controller.go:543","msg":"Reconcile succeeded","knative.dev/pod":"kafka-controller-7bc844bb6b-x4frd","knative.dev/controller":"knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.broker.Reconciler","knative.dev/kind":"eventing.knative.dev.Broker","knative.dev/traceid":"eae1957d-361e-4364-a22b-afa2af7241a2","knative.dev/key":"knative-eventing/onboarding-ci-kn-kafka-cluster","duration":0.337743497}
kafka-controller-7bc844bb6b-x4frd controller {"level":"debug","ts":"2022-04-20T11:19:23.200Z","logger":"kafka-broker-controller","caller":"prober/prober.go:63","msg":"Sending probe request","knative.dev/pod":"kafka-controller-7bc844bb6b-x4frd","scope":"prober","pod.metadata.name":"kafka-broker-receiver-7549f88579-jcmk6","address":"http://100.101.218.144:8080/knative-eventing/onboarding-ci-kn-kafka-cluster"}
kafka-controller-7bc844bb6b-x4frd controller {"level":"info","ts":"2022-04-20T11:19:23.201Z","logger":"kafka-broker-controller","caller":"prober/prober.go:86","msg":"Resource not ready","knative.dev/pod":"kafka-controller-7bc844bb6b-x4frd","scope":"prober","pod.metadata.name":"kafka-broker-receiver-7549f88579-jcmk6","address":"http://100.101.218.144:8080/knative-eventing/onboarding-ci-kn-kafka-cluster","statusCode":502}
```

So the IP is for kafka-broker-receiver  pod. To be honest we have no clue what might be wrong here. Also seems wierd to probe the pod directly instead of a service

 **Expected behavior**
The broker to become ready

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**
1.3.0
 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by pierDipi**
Istio doesn't work well when there is pod to pod communication.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes #2107

## Proposed Changes

- Prober targets service instead of pods directly

**Release Note**

```release-note
Receiver's prober targets services instead of pods directly to allow components to be part of an Istio mesh
```

### CODE REVIEW

**Comment by pierDipi** [comment]
```
[ERROR] Plugin org.apache.maven.plugins:maven-shade-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-shade-plugin:jar:3.3.0: Could not transfer artifact org.apache.maven.plugins:maven-shade-plugin:pom:3.3.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.3.0/maven-shade-plugin-3.3.0.pom: Connection reset -> [Help 1]
```
/test unit-tests_eventing-kafka-broker_main

**Comment by matzew** [comment]
LGTM

but, I'd like to see some feedback on if the patch worked in your environment, @LeonardAukea

**Comment by LeonardAukea** [comment]
@markhulia how is it going with the tests?

**Comment by pierDipi** [comment]
The patch worked https://github.com/knative-sandbox/eventing-kafka-broker/issues/2107#issuecomment-1117352526

/cherry-pick release-v1.4

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
Manual cherry pick into 1.2 branch: https://github.com/knative-sandbox/eventing-kafka-broker/pull/2180

**Pull request merged**
