### PR TITLE
[release-v1.7] [issue/2569] Check for kafka/network errors on finalizeKind

### PR DESCRIPTION
**Pull request by matzew**
Fixes #

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
@matzew there is a compilation error

**Comment by matzew** [comment]
> @matzew there is a compilation error

:monocle_face:

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
