### PR TITLE
Fix namespaced broker unit tests

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Address comments in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2817
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
Thanks @aliok !

Verify / verify / Verify Deps and Codegen is complaining: https://github.com/knative-sandbox/eventing-kafka-broker/actions/runs/3619471215/jobs/6100553008

**Comment by aliok** [comment]
@pierDipi 
Thanks for catching that!
Wanna re-approve?

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
