### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by pierDipi**
Run `./hack/update-deps.sh --upgrade` to get https://github.com/knative-sandbox/eventing-kafka/commit/63ae78472c947cd036ed2c054f03e4f3824cc440

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by aavarghese — APPROVED** [review]

**Comment by pierDipi** [comment]
> @matzew: If a child refuses to sleep during nap time, are they guilty of resisting a rest?

:upside_down_face: :smile:

**Comment by pierDipi** [comment]
This worked https://github.com/knative-sandbox/eventing-kafka-broker/pull/2123#issuecomment-1111112900

**Pull request merged**
