### PR TITLE
[release-0.26] Use Broker's own configmap for Kafka

### PR DESCRIPTION
**Pull request by mgencur**
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1591

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
with this commit: https://github.com/knative-sandbox/eventing-kafka-broker/pull/1594/commits/8a67c3401a204ce014bf33d8043646ac63c4278e the build test will fail, can you revert it?

Please, ignore GH actions, they're broken on old branches.

**Comment by mgencur** [comment]
Ah. OK, thanks! Pushed.

**Pull request merged**
