### PR TITLE
Revert channel parts of #1720

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Revert channel parts of #1720
- It breaks conformance tests
-

**Release Note**

```release-note
:wastebasket: Reverted the channel related changes done in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1720. The reference information for metrics was not built successfully for channels.
```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
@aliok can you create a PR against the 1.2 branch too?

/lgtm

**Comment by pierDipi** [comment]
> /cherypick release-1.2

FYI, If you want this PR to be part of tomorrow's patch release we need a patch before we can merge this one.

**Comment by aliok** [comment]
@pierDipi https://github.com/knative-sandbox/eventing-kafka-broker/pull/1835

Thanks!

**Pull request merged**
