### PR TITLE
Add upgrade test script placeholder

### PR DESCRIPTION
**Pull request by pierDipi**
To unblock other PRs, I'm adding a script that will make the upgrade
test job green.

## Proposed Changes

- Add upgrade test script placeholder

**Release Note**

```release-note
None
```

**Docs**

```
None
```

### CODE REVIEW

**Comment by pierDipi** [comment]
```
    operation.go:123: Failed while waiting for 1 endpoints in service trans-pod: did not reach the desired number of endpoints, got: 0: endpoints "trans-pod" not found
```
/retest

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
