### PR TITLE
k8s-service-trailing-slash-fix

### PR DESCRIPTION
**Pull request by Shashankft9**
Fixes #
The issue came up while fixing this: knative/pkg#2178, the tests are failing there because here the test cases expect a deadletter sink of k8s service with trailing slash.

## Proposed Changes

- Removing the trailing slash. 
- Replacing the strings with the const already there in objects_common.go

Please note that the tests will fail, blocked by the above mentioned PR merge.

### CODE REVIEW

**Comment by pierDipi** [comment]
@Shashankft9 can you please upgrade pkg to the latest so that tests can pass?

**Comment by matzew** [comment]
@Shashankft9  looks like there is some issue w/ the PR: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1115/pull-knative-sandbox-eventing-kafka-broker-build-tests/1422251468039131136

```
/home/prow/go/src/knative.dev/eventing-kafka-broker is out of date. Please run hack/update-codegen.sh
JUnit file /logs/artifacts/junit_D57NXlAJ.xml is created for reporting the test result
```

**Comment by Shashankft9** [comment]
closing in favor of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1123

**Pull request closed without merging**
