### PR TITLE
[release-1.4] Tracing tests for Kafka Broker

### PR DESCRIPTION
**Pull request by mgencur**
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2369

## Proposed Changes

- Backport the commit from main
- Update dependencies on knative.dev/eventing and knative.dev/eventing-kafka

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
The failure doesn't seem to be related to this PR
/retest-required

**Pull request closed without merging**
