### PR TITLE
Adding the Loom base modules with empty files.

### PR DESCRIPTION
**Pull request by debasishbsws**
Progress in #2928 

## Proposed Changes

- Added both loom-based modules with Java 19 as the latest Maven shade plugin does not support Java20 till now.
- Lower the Java version to 19 in tests as Every version has its exact preview feature and does not work in other versions.
Updates in latter comment

### CODE REVIEW

**Comment by debasishbsws** [comment]
Removed the shade plugin as it is not needed at least for now. and use `docker.io/library/eclipse-temurin:20-jre`

**Comment by debasishbsws** [comment]
@pierDipi It's ready to review.

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
