### PR TITLE
Bump Java from 14 to 15

### PR DESCRIPTION
**Pull request by pierDipi**
Java 14 isn't supported anymore.

## Proposed Changes

- Bump Java from 14 to 15

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
I think you should bump this one too https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/data-plane/pom.xml#L31

**Comment by pierDipi** [comment]
@slinkydeveloper done!

**Comment by pierDipi** [comment]
```Again Failed to create v1 broker "broker": Internal error occurred: failed calling webhook "webhook.eventing.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/defaulting?timeout=2s: no endpoints available for service "eventing-webhook"```

**Pull request merged**
