### PR TITLE
Debug sacura job

### PR DESCRIPTION
**Pull request by pierDipi**
Part of https://github.com/knative-sandbox/eventing-kafka-broker/issues/556

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

/cc pierDipi

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Since this job is extremely flaky, can we disable it until we find why it's flaky?

**Comment by pierDipi** [comment]
@slinkydeveloper let's disable it after the release if we don't find a solution until then.

I create a program that does some correlation of the logs by taking sacura output and looking into receiver and dispatcher logs, here is an example output:

```
-----> 609c0a35-dc32-4d29-932f-eb7aad9200c4
{"@timestamp":"2021-02-16T08:17:07.248Z","@version":"1","message":"received event event=CloudEvent{id='609c0a35-dc32-4d29-932f-eb7aad9200c4', source=http://example.com/source, type='com.example.FullEvent', datacontenttype='text/json', dataschema=http://example.com/schema, subject='topic', time=2020-03-21T12:34:56.780Z, data=JsonCloudEventData{node=\"hello\"}, extensions={exstring=exstring, extime=2020-03-21T12:34:56.78Z, exint=42, exurl=http://example.com/source, exbinary=AAECAw==, exbool=true}}","logger_name":"dev.knative.eventing.kafka.broker.receiver.CloudEventRequestToRecordMapper","thread_name":"vert.x-eventloop-thread-0","level":"DEBUG","level_value":10000,"event":{"data":{"node":"hello"},"id":"609c0a35-dc32-4d29-932f-eb7aad9200c4","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":1584794096.780000000,"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2021-02-16T08:17:07.263Z","@version":"1","message":"Record produced topic=knative-broker-sacura-broker partition=4 offset=10115 value=CloudEvent{id='609c0a35-dc32-4d29-932f-eb7aad9200c4', source=http://example.com/source, type='com.example.FullEvent', datacontenttype='text/json', dataschema=http://example.com/schema, subject='topic', time=2020-03-21T12:34:56.780Z, data=JsonCloudEventData{node=\"hello\"}, extensions={exstring=exstring, extime=2020-03-21T12:34:56.78Z, exint=42, exurl=http://example.com/source, exbinary=AAECAw==, exbool=true}} headers=[] path=/sacura/broker","logger_name":"dev.knative.eventing.kafka.broker.receiver.RequestMapper","thread_name":"vert.x-eventloop-thread-0","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":4,"offset":10115,"value":{"data":{"node":"hello"},"id":"609c0a35-dc32-4d29-932f-eb7aad9200c4","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":1584794096.780000000,"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]},"headers":[],"path":"/sacura/broker"}
{"@timestamp":"2021-02-16T08:17:18.863Z","@version":"1","message":"Handling record topic=knative-broker-sacura-broker partition=4 headers=[io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@16ee3df2, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2e38b363, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2491644d, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@20c90911, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@472fa157, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2c67b17a, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@3fb0bb7, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@6b120b58, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@518d3a74, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@4070ad5e, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1b0da054, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@60be20a6, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@5858f85f, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1d07b457] offset=10115 event=CloudEvent{id='609c0a35-dc32-4d29-932f-eb7aad9200c4', source=http://example.com/source, type='com.example.FullEvent', datacontenttype='text/json', dataschema=http://example.com/schema, subject='topic', time=2020-03-21T12:34:56.780Z, data=BytesCloudEventData{value=[34, 104, 101, 108, 108, 111, 34]}, extensions={exstring=exstring, extime=2020-03-21T12:34:56.78Z, exint=42, exurl=http://example.com/source, exbinary=AAECAw==, exbool=true}}","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.RecordDispatcher","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":4,"headers":[{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"offset":10115,"event":{"data":{},"id":"609c0a35-dc32-4d29-932f-eb7aad9200c4","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":1584794096.780000000,"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2021-02-16T08:17:18.863Z","@version":"1","message":"Record match filtering topic=knative-broker-sacura-broker partition=4 headers=[io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@16ee3df2, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2e38b363, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2491644d, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@20c90911, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@472fa157, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2c67b17a, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@3fb0bb7, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@6b120b58, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@518d3a74, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@4070ad5e, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1b0da054, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@60be20a6, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@5858f85f, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1d07b457] offset=10115 event=CloudEvent{id='609c0a35-dc32-4d29-932f-eb7aad9200c4', source=http://example.com/source, type='com.example.FullEvent', datacontenttype='text/json', dataschema=http://example.com/schema, subject='topic', time=2020-03-21T12:34:56.780Z, data=BytesCloudEventData{value=[34, 104, 101, 108, 108, 111, 34]}, extensions={exstring=exstring, extime=2020-03-21T12:34:56.78Z, exint=42, exurl=http://example.com/source, exbinary=AAECAw==, exbool=true}}","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.RecordDispatcher","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":4,"headers":[{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"offset":10115,"event":{"data":{},"id":"609c0a35-dc32-4d29-932f-eb7aad9200c4","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":1584794096.780000000,"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
{"@timestamp":"2021-02-16T08:17:32.356Z","@version":"1","message":"Successfully sent event to subscriber topic=knative-broker-sacura-broker partition=4 headers=[io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@16ee3df2, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2e38b363, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2491644d, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@20c90911, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@472fa157, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@2c67b17a, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@3fb0bb7, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@6b120b58, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@518d3a74, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@4070ad5e, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1b0da054, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@60be20a6, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@5858f85f, io.vertx.kafka.client.producer.impl.KafkaHeaderImpl@1d07b457] offset=10115 event=CloudEvent{id='609c0a35-dc32-4d29-932f-eb7aad9200c4', source=http://example.com/source, type='com.example.FullEvent', datacontenttype='text/json', dataschema=http://example.com/schema, subject='topic', time=2020-03-21T12:34:56.780Z, data=BytesCloudEventData{value=[34, 104, 101, 108, 108, 111, 34]}, extensions={exstring=exstring, extime=2020-03-21T12:34:56.78Z, exint=42, exurl=http://example.com/source, exbinary=AAECAw==, exbool=true}}","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.RecordDispatcher","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":4,"headers":[{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"offset":10115,"event":{"data":{},"id":"609c0a35-dc32-4d29-932f-eb7aad9200c4","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","time":1584794096.780000000,"dataContentType":"text/json","dataSchema":"http://example.com/schema","specVersion":"V1","extensionNames":["exstring","extime","exint","exurl","exbinary","exbool"],"attributeNames":["datacontenttype","subject","specversion","id","source","time","type","dataschema"]}}
```

The event seems to be successfully sent to the sink by looking at the logs but it's marked as lost by sacura.

There could be 2 issues:
- sacura is buggy
- `Successfully sent event ...` is wrong

**Comment by slinkydeveloper** [comment]
@pierDipi can you open a pr to disable sacura? I'll rebase the other prs and merge it

**Comment by pierDipi** [comment]
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
Worked again.

**Comment by pierDipi** [comment]
I'm rebasing/

**Comment by pierDipi** [comment]
3/3 worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
> `Successfully sent event ...` is wrong

I checked and this is _not_ wrong.

**Comment by pierDipi** [comment]
4/4 worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
5/5 worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by pierDipi** [comment]
6/6 worked, retesting
/test pull-knative-sandbox-eventing-kafka-broker-integration-tests

**Comment by slinkydeveloper** [comment]
/lgtm
/approve

I'm going to rebase all the other pending PRs, let's see if it works :smile:

**Pull request merged**
