### PR TITLE
Now codegen verifies the THIRD-PARTY.txt file

### LINKED ISSUE #844: Third party file should be checked by the codegen
**Problem**
We have a third party file codegenerated by maven which is not checked by our codegen, generating merge conflicts

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Knative developer

**Exit Criteria**
Third party file should be checked by the codegenerator check

**Time Estimate (optional):** 
1

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Fixes #844

## Proposed Changes

- :gift: Copy pasted hack from https://github.com/dependabot/dependabot-actions-workflow to let dependabot update the third party licenses file. I'm not sure it works, but I guess it's worth a try :smile: 
- :gift: Now the verify codegen script checks the THIRD-PARTY.txt file too

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — DISMISSED** [review]
Let's try 🤷

**Comment by pierDipi** [comment]
Actually, In the [update codegen script](https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/hack/update-codegen.sh)  we need to generate this file, otherwise this check is not valid.

/hold

**Comment by slinkydeveloper** [comment]
@pierDipi good catch, i pushed that change

**Review by pierDipi — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
