### PR TITLE
Bump to Strimzi 0.34.0 and using kafka 3.4

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- Bump to Strimzi 0.33.2 and using kafka 3.4

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

Asking this again, but we should have some automation :)

**Comment by matzew** [comment]
> Asking this again, but we should have some automation :)

I agree, but it's often a mix of either just the operator, or the operand, or both. If you want to automate go ahead

**Comment by aliok** [comment]
> If you want to automate go ahead

Nope 🕺 😆

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
