### PR TITLE
Implement Trigger.Spec.DeliverySpec

### LINKED ISSUE #578: Implement Trigger.Spec.DeliverySpec
**Problem**

Triggers have a new field `Trigger.Spec.DeliverySpec` that overrides the `Broker.Spec.DeliverySpec`, we should implement it.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Event Consumer

**Exit Criteria**
All tests pass.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
2

**Additional context (optional)**

1. https://github.com/knative/eventing/pull/4654

/help

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes #578 

I'd wait for an E2E test from the `eventing` repository.

## Proposed Changes

- Implement Trigger.Spec.DeliverySpec

**Release Note**

```release-note
:gift: Add support for Trigger.Spec.DeliverySpec
```

/kind enhancement

### CODE REVIEW

**Review by slinkydeveloper — APPROVED** [review]
Not much of a difference for us, unhold at your will

/unhold

**Comment by pierDipi** [comment]
It needs lgtm tho.
/unhold

**Comment by pierDipi** [comment]
A PR in eventing breaks a test https://github.com/knative/eventing/pull/4843

**Comment by pierDipi** [comment]
This should fix it https://github.com/knative-sandbox/eventing-kafka-broker/pull/627

**Pull request merged**
